# Generated by Django 3.1.6 on 2021-02-17 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('everyday_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ednote',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
